// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjwbrqpjxpzzwsodzglr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qd2JycXBqeHB6endzb2R6Z2xyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMTMxOTMsImV4cCI6MjA3MDU4OTE5M30.8alIYlXGUdHAkc9yAlN-jeAQTRWq2F0PjXnKyf9cXfw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    // Note: Supabase manages session duration automatically
    // Sessions are automatically refreshed for optimal persistence
  }
});